name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: ${{ vars.GO_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - run: go mod download

      - run: go build ./cmd/kubectl-limitrange

      - uses: actions/upload-artifact@v3
        with:
          name: kubectl-limitrange
          path: ./kubectl-limitrange

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - run: go mod download

      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=30m
          version: v1.61
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true 

      - run: go mod download

      - run: go test ./... -v

      - name: Check code formatting
        run: go fmt ./...