name: Build and Create Multi-Platform Releases

on:
  push:
    branches:
      - main

env:
  GO_VERSION:  ${{ vars.GO_VERSION }}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        os: [linux-amd64, macos-amd64, windows-amd64]
        include:
          - os: linux-amd64
            ext: ''
            checksum_cmd: sha256sum
          - os: macos-amd64
            ext: ''
            checksum_cmd: shasum -a 256
          - os: windows-amd64
            ext: '.exe'
            checksum_cmd: CertUtil -hashfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o kubectl-lr${{ matrix.ext }} ./cmd/kubectl-limitrange

      - name: Create archive for release
        run: |
          if [[ "${{ matrix.os }}" == "windows-amd64" ]]; then
            zip kubectl-lr-${{ matrix.os }}.zip kubectl-lr${{ matrix.ext }}
          else
            tar -czvf kubectl-lr-${{ matrix.os }}.tar.gz kubectl-lr${{ matrix.ext }}
          fi

      - name: Generate SHA256 checksum
        run: |
          if [[ "${{ matrix.os }}" == "windows-amd64" ]]; then
            ${{ matrix.checksum_cmd }} kubectl-lr-${{ matrix.os }}.zip > kubectl-lr-${{ matrix.os }}.sha256
          else
            ${{ matrix.checksum_cmd }} kubectl-lr-${{ matrix.os }}.tar.gz > kubectl-lr-${{ matrix.os }}.sha256
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubectl-lr-${{ matrix.os }}
          path: |
            kubectl-lr-${{ matrix.os }}.tar.gz
            kubectl-lr-${{ matrix.os }}.zip
            kubectl-lr-${{ matrix.os }}.sha256

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display checksums for debugging
        run: cat kubectl-lr-*.sha256

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kubectl-lr-linux-amd64.tar.gz
            kubectl-lr-linux-amd64.sha256
            kubectl-lr-macos-amd64.tar.gz
            kubectl-lr-macos-amd64.sha256
            kubectl-lr-windows-amd64.zip
            kubectl-lr-windows-amd64.sha256
          tag_name: "v1.0.0"  # Replace with appropriate tag logic if needed
          name: Release ${{ github.ref_name }}
          body: |
            Multi-platform binaries for Linux, macOS, and Windows.
            SHA256 Checksums:
            ```
            $(cat kubectl-lr-linux-amd64.sha256)
            $(cat kubectl-lr-macos-amd64.sha256)
            $(cat kubectl-lr-windows-amd64.sha256)
            ```
          draft: true  # Change to false to automatically publish the release
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
