name: Build and Create Multi-Platform Releases

on:
  push:
    branches:
      - main

env:
  GO_VERSION: ${{ vars.GO_VERSION }}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        os: [linux, macos, windows]
        include:
          - os: linux
            ext: ''
            archive_ext: 'tar.gz'
          - os: macos
            ext: ''
            archive_ext: 'tar.gz'
          - os: windows
            ext: '.exe'
            archive_ext: 'zip'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -o kubectl-lr${{ matrix.ext }} ./cmd/kubectl-limitrange

      - name: Create archive for release
        run: |
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            zip kubectl-lr-${{ matrix.os }}-amd64.zip kubectl-lr${{ matrix.ext }}
          else
            tar -czvf kubectl-lr-${{ matrix.os }}-amd64.tar.gz kubectl-lr${{ matrix.ext }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubectl-lr-${{ matrix.os }}-amd64
          path: |
            kubectl-lr-${{ matrix.os }}-amd64.tar.gz
            kubectl-lr-${{ matrix.os }}-amd64.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts for debugging
        run: ls -l artifacts

      - name: List all files
        run: find artifacts -type f

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/kubectl-lr-linux-amd64/kubectl-lr-linux-amd64.tar.gz
            artifacts/kubectl-lr-macos-amd64/kubectl-lr-macos-amd64.tar.gz
            artifacts/kubectl-lr-windows-amd64/kubectl-lr-windows-amd64.zip
          tag_name: "v1.0.0"  # Replace with appropriate tag logic if needed
          name: Release ${{ github.ref_name }}
          body: |
            Multi-platform binaries for Linux, macOS, and Windows.
          draft: true  # Change to false to automatically publish the release
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
